### PR TITLE
Remove unneeded patches as of 2019.9.29

### LINKED ISSUE #1130: E1010 GetAtt check fails on AWS::SageMaker::CodeRepository resource
*cfn-lint version*: `0.24.1`

*Description of issue*

`GetAtt` (E1010) lint rule fails with false positive saying an instance of `AWS::SageMaker::CodeRepository` does not have an attribute `CodeRepositoryName`. However, the [official resource documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-coderepository.html#aws-resource-sagemaker-coderepository-return-values) indicates otherwise. Presumably this is an issue with the CloudSpecs. However, `cfn-lint -u` did not resolve the issue.

Minimal template to replicate the issue:

```lang=yaml
AWSTemplateFormatVersion: '2010-09-09'

Parameters:

  SecurityGroup:
    Type: String

  SubnetId:
    Type: String

  RoleArn:
    Type: String

Resources:

  NotebookRepositoryLink:
    Type: AWS::SageMaker::CodeRepository
    Properties:
      GitConfig:
        RepositoryUrl: https://example.com/repo/

  Notebook:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      DefaultCodeRepository: !GetAtt NotebookRepositoryLink.CodeRepositoryName
      DirectInternetAccess: Disabled
      InstanceType: ml.t3.xlarge
      RootAccess: Disabled
      RoleArn: !Ref RoleArn
      SecurityGroupIds:
      - !Ref SecurityGroup
      SubnetId: !Ref SubnetId
```

Running `cfn-lint test_template.yml` yields:

```
E1010 Invalid GetAtt NotebookRepositoryLink.CodeRepositoryName for resource Notebook
test_template.yml:25:7
```

Expected output - no linter errors.

Temporary workaround is to disable this rule on the resource.

### PR DESCRIPTION
**Pull request by kddejong**
*Issue #, if available:*
Fix #1130 
*Description of changes:*
- Update patch specs to what is in spec version 6.2.0

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by PatMyron** [comment]
https://github.com/aws-cloudformation/cfn-python-lint/pull/596
https://github.com/aws-cloudformation/cfn-python-lint/pull/704
https://github.com/aws-cloudformation/cfn-python-lint/pull/1006

@kddejong is there a script to check or generate removal of unnecessary patches? Could check if there's a diff after applying each patch

**Comment by kddejong** [comment]
Not really.  I usually just manually validate but it would be nice to have something. 
#1201 to help remove some patches

**Comment by PatMyron** [comment]
Although a patched-in resource type could be added to the official spec with a new property or something similar, so I guess there will always be some manual checking

**Comment by chuckmeyer** [comment]
It's a tough one to automate, to be sure (much like that patching itself)

**Pull request merged**
