### PR TITLE
Build a standalone package for offline installation

### PR DESCRIPTION
**Pull request by jakub-bochenski**
*Description of changes:*

A convenience for offline or automated installations on Linux or macOS.
Same as the bundle for AWS CLI, which it's based on - https://github.com/aws/aws-cli/blob/1.16.314/scripts/make-bundle

It would be useful for me to have this published officially, even if only on Github (no need to host it on S3 like the AWS CLI bundle).

```
The goal of this script is simple:
  * Create a self contained install of the CLI that
  has requires no external resources during installation.
It does this by using all the normal python tooling
(virtualenv, pip) but provides a simple, easy to use
interface for those not familiar with the python
ecosystem.
```

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jakub-bochenski** [comment]
Would be nice to at least get some kind of reply. Do you even consider merging this?

**Comment by kddejong** [comment]
Sorry for the delay.  Looking into this today.  

So to add on to this would we also add something to pipeline to push the packages to git?

**Comment by jakub-bochenski** [comment]
Thanks!

> So to add on to this would we also add something to pipeline to push the packages to git?

Probably yes. Though I have no idea about the pipeline setup in this project, that's why I didn't do it.

**Comment by kddejong** [comment]
Was able to validate this works.  Double checking all the code one more time.

**Pull request merged**
