### PR TITLE
AWS::DocDB::DBCluster.EngineVersion AllowedValues expansion (4.0)

### PR DESCRIPTION
**Pull request by troyfactor4**
*Issue #, if available: n/a

*Description of changes: Adds DocumentDB 4.0 to the allowed Engine types

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by kddejong** [comment]
@troyfactor4 if you make the change here https://github.com/aws-cloudformation/cfn-python-lint/blob/master/src/cfnlint/data/ExtendedSpecs/all/03_value_types.json#L166-L170 we can do the rest of the changes you made.  We use JSON patching to patch in the values to the specs as we do the update.

**Comment by PatMyron** [comment]
https://github.com/aws-cloudformation/cfn-python-lint/blob/620d14ede12e340497580b47124c06d856b06104/src/cfnlint/data/ExtendedSpecs/all/03_value_types.json#L166-L169

 Also from looking at the documentation, do you know if it should be `4.0` instead of [`4.0.0`](https://docs.aws.amazon.com/documentdb/latest/developerguide/db-cluster-create.html#db-cluster-create-con)?

**Comment by troyfactor4** [comment]
@kddejong - gotcha. Figured there had to be a better way. There it is.

@PatMyron - yeah I've been using "4.0" in a few scripts over the last few days and it works. Documented here: "https://docs.aws.amazon.com/documentdb/latest/developerguide/compatibility.html#compatibility-getstarted"

**Comment by troyfactor4** [comment]
@PatMyron - just checked out the page you linked on 4.0.0. Interesting, I wonder if both values work?

**Comment by PatMyron** [comment]
> @PatMyron - just checked out the page you linked on 4.0.0. Interesting, I wonder if both values work?

Yeah both of these worked, so maybe add both:
```yaml
Resources:
  DocDBDBCluster:
    Type: AWS::DocDB::DBCluster
    Properties:
      MasterUsername: MasterUsername
      MasterUserPassword: MasterUserPassword
      EngineVersion: 4.0.0
```
```yaml
Resources:
  DocDBDBCluster:
    Type: AWS::DocDB::DBCluster
    Properties:
      MasterUsername: MasterUsername
      MasterUserPassword: MasterUserPassword
      EngineVersion: 4.0
```

**Comment by troyfactor4** [comment]
Done. I've reverted all of those initial changes and added both "4.0" and 4.0.0" to the json patching file.

**Review by PatMyron — APPROVED** [review]

**Pull request merged**
