### PR TITLE
Add python 3.8 support

### PR DESCRIPTION
**Pull request by chenrui333**
*Description of changes:*

Add python 3.8 support

### CODE REVIEW

**Comment by kddejong** [comment]
This looks good to me.  Thanks for doing this.

**Comment by chenrui333** [comment]
@kddejong I just found that you did the similar thing in #1289, but i guess we can take a granular step of add/delete.

**Comment by kddejong** [comment]
exactly.  Completely cool with that approach.  I need to do some more planning on the 3.4 side of the world anyways.

**Comment by chenrui333** [comment]
Totally agree!

**Comment by kddejong** [comment]
@chenrui333 looks like an issue outside of your control.  I'll try to get a fix in shortly then get this in after.

**Comment by chenrui333** [comment]
Thanks @kddejong!

**Pull request merged**
