### PR TITLE
CloudFormation Resource Specification 18.7.0

### PR DESCRIPTION
**Pull request by zganger**
I have a project using elasticache, and cfn-lint in my CI declined my change to use `cache.m6g` instance types that were [released](https://aws.amazon.com/about-aws/whats-new/2020/10/amazon-elasticache-now-supports-m6g-and-r6g-graviton2-based-instances/) on October 8 for some regions.

*Issue #, if available:*

*Description of changes:*
I used [`scripts/update_specs_from_pricing.py`](https://github.com/aws-cloudformation/cfn-python-lint/blob/master/scripts/update_specs_from_pricing.py) to update the available instance types across regions.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by PatMyron** [comment]
Can also workaround with [resource-level ignores](https://github.com/aws-cloudformation/cfn-python-lint#resource-based-metadata) until these are released as well:

```yaml
  Resource:
    Type: AWS::ElastiCache::ReplicationGroup
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
          - E3030
```

**Comment by zganger** [comment]
Thanks! That's good to know. Hopefully this is still a helpful PR and will solve this for other people as well.

**Comment by PatMyron** [comment]
@zganger definitely, going to add our other weekly maintenance scripts to this PR as well:
```bash
scripts/update_specs_from_pricing.py # requires Boto3 and Credentials
scripts/update_specs_services_from_ssm.py # requires Boto3 and Credentials
cfn-lint --update-specs # https://github.com/aws-cloudformation/cfn-python-lint/pull/1383\#issuecomment-629891506
cfn-lint --update-iam-policies
cfn-lint --update-documentation
```

**Comment by zganger** [comment]
sounds great, thanks!

**Review by kddejong — APPROVED** [review]

**Pull request merged**
