### PR TITLE
Add new rule to check for deprecated Lambda Runtimes (W2530)

### PR DESCRIPTION
**Pull request by fatbasstard**
*Issue https://github.com/aws-cloudformation/cfn-python-lint/issues/898 if available:*

Add a rule to give a Warning is a deprecated Runtime is used:

**features**
- A Warning since we cannot detect creates/updates in Lambda functions based on a static file.
- Time aware rule, no cfn-python-lint release required for the rule to become enable.
- Warning is raised when the `Deprecated (Update)` date is passed
- Support for "Rule Configuration": if `check_eol_date=true` is specified, the rule triggers on the EOL date. (CLI example `W2530:check_eol_date=true`
- Warning gives advice and the new Runtime to use. Decised to go for the "latest" version (in case of Node: `NodeJs10.x`)

**Might be interesting to make this `experimental` first **

Updated the tests to reflect this (we used `nodejs6.3` in most of our tests). Minor "risk" in this is that once NodeJS10 becomes dedicated, the tests will start failing. Accepting this for now as an acceptable risk.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by kddejong** [comment]
The only thing I keep thinking about is personally I would like to know that I may have an issue before the issue occurs.  I don't want an error as I still have time to fix (past the EOL Date) it but I want to be able to visualize this issue before it becomes an issue.

Should there be different class rules for this?  
Should it be an Error if the deprecated date has occurred?
Could it be an Info level warning if the EOL has occurred?

**Comment by fatbasstard** [comment]
@kddejong Check on my explanation in the Issue as well.

- The config toggle allows this somewhat. Trigger on the EOL date, or on the Deprecated date.
- Error is not an option, because (What I understand from it) the Lambda cannot be updated, but the rest of the template can. An Error is not true in that case
- Could remove the config and add that as an Informational rule (Just a decision)

**Comment by cmmeyer** [comment]
I like the idea of moving the Lambda runtime lifecycle info into its own file (or enriching the runtime data in the spec) and then we could have two rules around eol and deprecated).

**Comment by fatbasstard** [comment]
Easy to move into a file...

**Comment by fatbasstard** [comment]
Closing in favor of https://github.com/aws-cloudformation/cfn-python-lint/pull/915

**Pull request closed without merging**
